<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AdminConsoleFor1C.Core\AdminConsoleFor1C.Core.csproj" />
    <ProjectReference Include="..\AdminConsoleFor1C.Application\AdminConsoleFor1C.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="10.0.8" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
